name = "ts_auto_external"
version = "1.0.0"

description = "Generate FFI Gleam Functions for TypeScript code automatically"
licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "gleam_ts_auto_external" }

internal_modules = [
  "ts_auto_external/internal",
  "ts_auto_external/internal/*",
  "dev",
  "dev/*",
]

target = "javascript"

[javascript]
runtime = "deno"

[javascript.deno]
allow_all = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
hexdocs_offline = ">= 1.0.5 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
filepath = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
