name = "ts_auto_ffi"
version = "1.0.0"

description = "Generate FFI Gleam Functions for TypeScript code automatically"
licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "gleam_ts_auto_ffi" }

internal_modules = [
  "ts_auto_ffi/internal",
  "ts_auto_ffi/internal/*",
  "dev",
  "dev/*",
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
hexdocs_offline = ">= 1.0.5 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
